version: 3

build_arg_defaults: 
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies: 
  galaxy: requirements.yml

images: 
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest
