---
- name: Deploy Nginx container using Podman
  hosts: all
  become: true
  tasks:
    - name: Pull nginx image
      containers.podman.podman_image:
        name: "{{ container_image | default('docker.io/library/nginx') }}:{{ container_tag | default('latest') }}"
        force: true
        state: present

    - name: Create and start nginx container
      containers.podman.podman_container:
        name: nginx-server
        image: "{{ container_image | default('docker.io/library/nginx') }}:{{ container_tag | default('latest') }}"
        state: started
        ports:
          - "{{ host_port }}:80"
        restart_policy: always
        generate_systemd:
          path: /etc/systemd/system
          restart_policy: always
          names: true

    - name: Enable and start systemd service
      systemd:
        name: container-nginx-server
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Add {{ host_port }} ports to firewall
      firewalld:
        port: "{{ host_port }}/tcp"
        state: enabled
        immediate: true
        permanent: true
      become: yes

    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
